# Generated by Django 4.2 on 2023-06-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=20)),
                ('weekend', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('image', models.ImageField(blank=True, default='mentors/default.jpg', upload_to='mentors/')),
                ('direction', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('UX/UI', 'UX/UI'), ('Android', 'Android'), ('IOS', 'IOS')], max_length=10)),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=5)),
                ('group', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=15)),
                ('about_me', models.TextField()),
                ('contact', models.URLField()),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.employment')),
                ('skills', models.ManyToManyField(to='mentors.skills')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
        ),
    ]
