# Generated by Django 4.2 on 2023-06-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='direction',
            new_name='directions',
        ),
    ]
