# Generated by Django 4.2 on 2023-06-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='directions',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('UX/UI', 'UX/UI'), ('Android', 'Android'), ('IOS', 'IOS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=255),
        ),
    ]
